### ISSUE TITLE
JustTransmit.ino does not compile.

### ISSUE THREAD

**Issue by nvahalik** [EnhancedRadioDevices/HamShield#16]
> Arduino: 1.6.9 (Mac OS X), Board: "Arduino/Genuino Uno"
> sketch/JustTransmit.ino.cpp.o: In function `setup':
> /Users/nvahalik/Downloads/HamShield-master/examples/JustTransmit/JustTransmit.ino:31: undefined reference to`HamShield::setChanMode(unsigned int)'
> collect2: error: ld returned 1 exit status
> exit status 1
> Error compiling for board Arduino/Genuino Uno.

Looks like these functions are [commented out in Hamshield.cpp](https://github.com/EnhancedRadioDevices/HamShield/blob/master/HamShield.cpp#L420-L433).

**Comment by mogar** [comment]
These are now fixed in the latest release.
