### ISSUE TITLE
Parrot.ino fails to compile due to memory constraints.

### ISSUE THREAD

**Issue by nvahalik** [EnhancedRadioDevices/HamShield#17]
Using the latest release of the Arduino software for Mac (1.6.9 at time of writing) and using an Uno R3.

> Sketch uses 7,296 bytes (22%) of program storage space. Maximum is 32,256 bytes.
> Global variables use 2,518 bytes (122%) of dynamic memory, leaving -470 bytes for local variables. Maximum is 2,048 bytes.

**Comment by AF6TF** [comment]
Same here. Must have been written with a different Arduino CPU in mind.

**Comment by mogar** [comment]
This example has been removed.
