### ISSUE TITLE
Add a library.properties file to repo

### ISSUE THREAD

**Issue by cshotton** [EnhancedRadioDevices/HamShield#20]
Adding a library.properties file will help users know what version of the HamShield library they have installed and will make it easier to download/install updates in the future.

See https://github.com/adafruit/Adafruit_NeoPixel/blob/master/library.properties as an example.
Here's the spec:  https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.5:-Library-specification

**Comment by nick6x** [comment]
The HamShield library now has a library.properties file. Thanks for the heads-up.
