### ISSUE TITLE
Arduino IDE doesn't like dashes in project or file names

### ISSUE THREAD

**Issue by JeffMelton** [EnhancedRadioDevices/HamShield#21]
Really a minor thing: The two AFSK examples and the APRS-Beacon example should ideally be renamed. Change the dashes to underscores, or remove them altogether, and the IDE will be happy again. I'm using the version of the IDE in Ubuntu's repos, so I suppose it's possible that's a bug. Underscores would match the SSTV_M1_Static directory naming convention in any case.

**Comment by nick6x** [comment]
I've updated the names of those examples so that they now use underscores instead of dashes.
