### ISSUE TITLE
Compile Errors 'TIFR2' was not declared in this scope AFSK_SerialMessenger (and others) 

### ISSUE THREAD

**Issue by Temtel** [EnhancedRadioDevices/HamShield#26]
Errors are failing compile of some sketches for several boards. Tested compiles for other boards as well, following is an example of the output:

<pre>
Arduino: 1.6.12 (Windows 7), Board: "Arduino Leonardo"

In file included from C:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino/Arduino.h:30:0,

                 from sketch\AFSK_SerialMessenger.ino.cpp:1:

C:\Users\JT\Documents\Arduino\libraries\HamShield-master\examples\AFSK_SerialMessenger\AFSK_SerialMessenger.ino: In function 'void TIMER2_OVF_vect()':

C:\Users\JT\Documents\Arduino\libraries\HamShield-master\examples\AFSK_SerialMessenger\AFSK_SerialMessenger.ino:141:5: warning: 'TIMER2_OVF_vect' appears to be a misspelled signal handler, missing __vector prefix [-Wmisspelled-isr]

 ISR(TIMER2_OVF_vect) {

     ^

AFSK_SerialMessenger:142: error: 'TIFR2' was not declared in this scope

   TIFR2 = _BV(TOV2);

   ^

In file included from c:\program files (x86)\arduino\hardware\tools\avr\avr\include\avr\io.h:99:0,

                 from c:\program files (x86)\arduino\hardware\tools\avr\avr\include\avr\pgmspace.h:90,

                 from C:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino/Arduino.h:28,

                 from sketch\AFSK_SerialMessenger.ino.cpp:1:

AFSK_SerialMessenger:142: error: 'TOV2' was not declared in this scope

   TIFR2 = _BV(TOV2);

               ^

exit status 1
'TIFR2' was not declared in this scope

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences
</pre>

Results for compile of AFSK_SerialMessenger by board:
<pre>
Failed  Yun(TIFR2 was not declared in this scope)
Success Uno
Success Duemilanove or Decimelia
Success Nano
Success Mega or Mega 2560
Success Mega ADK
Failed Leonardo(TIFR2 was not declared in this scope)
Failed Micro(TIFR2 was not declared in this scope)
Failed Esplora (TIFR2 was not declared in this scope)
Success Mini
Success Ethernet
Success Fio
Success BT
Failed Lillypad USB (TIFR2 was not declared in this scope)
Success Lillypad
Success Pro or Pro Mini
Failed NG or older (Not enough memory)
Failed Robot Control (TIFR2 was not declared in this scope)
Failed Robot Motor (TIFR2 was not declared in this scope)
Failed Gemma (Serial was not declared)
</pre>

**Comment by mogar** [comment]
Thanks for the exhaustive report, Temtel.

At the moment, the default HamShield library works with the Leonardo (and should work with the other variants whose error was TIFR2). However, a lot of the code that requires the DDS won't work yet. The DDS requires hardware timers, and different Arduino variants have different timers. The upshot of this is that none of the AFSK examples (and some others) currently support non-ATMEGA328 Arduino variants. 

We're working on adding support for the timers in the other variants, but that's a few weeks out at least.

**Comment by skitzoid799** [comment]
That makes sense-- thank you.

**Comment by jimcam** [comment]
@mogar  Thanks for working on supporting DDS on YUN and Leonardo.  I am hoping to use my YUN soon!

**Comment by mogar** [comment]
We've decided not to officially support the Yun or Leonardo because the timers required interfere with millis() and delay(). Either we mess up the time base of the arduino, or we can't hit the frequencies needed for AFSK with the pin 3 PWM.

If you'd like to do the work yourself (and possibly mess up timing on the arduino for other functions), then porting the DDS and AFSK code to the arduino is mostly an exercise in swapping all the Timer 2 registers to Timer 0 registers in DDS.c and packet.c.
