### ISSUE TITLE
Addressing two shields on one Arduino

### ISSUE THREAD

**Issue by AF6TF** [EnhancedRadioDevices/HamShield#28]
For my HamShield repeater project, I'm stumped on how to code the calls to each HamShield.  We've already discussed the use of two pins for the CS of each HamShield so I've got the hardware part handled.

I think the correct way is to define TX_Radio_PIN=4 and RX_Radio_PIN=5 based on the CS notes from the HamShield schematic.

**Comment by mogar** [comment]
In the HamShield_comms.cpp file, you'll see that all of the HamShield communications functions get called with a devAddr input. That devAddr is the CS pin used by the HamShield. That's how the specific HamShield is addressed on a per-communication basis.

The specific devAddr is set when you create a HamShield object. In most of the examples, we do something like:

    HamShield radio;

Which sets devAddr to the default. To set a different devAddr, you need to use the non-default constructor for the class. Try the following:

    HamShield radio = new HamShield(your_CS_pin_num);
