### ISSUE TITLE
Support for Intel Edison

### ISSUE THREAD

**Issue by jimcam** [EnhancedRadioDevices/HamShield#32]
Attempting to build an APRS iGate.   (Wireless) Internet connectivity is essential.   Intel Edison on the Arduino carrier board makes a compelling package.  Needs DDS timer support for this to work.

This configuration may also support an IRPL node.   This needs investigation.

**Comment by mogar** [comment]
Fully agreed. Edison support is probably behind Leonardo in priority, but we do intend to do that.

**Comment by jimcam** [comment]
I'm ready to integrate the HamShield with the Intel Edison Arduino.   I have all the parts but am missing the foundation SW.   I would like to get BLE sensor data sent as telemetry data over APRS.   I'm pulling together the BLE listener pieces on the Edison but I still missing the DDS timer support to run APRS.

**Comment by jimcam** [comment]
I'm ready to integrate the HamShield with the Intel Edison Arduino. I have all the parts but am missing the foundation SW. I would like to get BLE sensor data sent as telemetry data over APRS. I'm pulling together the BLE listener pieces on the Edison but I still missing the DDS timer support to run APRS.

**Comment by mogar** [comment]
Closing this since Intel Edison is no longer available.

Long term, we do want to break out the timing functions to make HamShield more extensible for other architectures.
