### ISSUE TITLE
Unclear documentation for DTMF decoding/encoding

### ISSUE THREAD

**Issue by cjlawson02** [EnhancedRadioDevices/HamShield#38]
I can't seem to find documentation for DTMF usage other than scattered references in the wiki.

**Comment by mogar** [comment]
We are working on a DTMF example sketch to show how it's used.

**Comment by cjlawson02** [comment]
Sounds good

**Comment by marcushammar** [comment]
Thanks! Please include an example on how to receive DTMF. I plan to control our gingerbread house next Christmas with an amateur radio and DTMF tones.

**Comment by mogar** [comment]
I've pushed a few commits to master that show to use DTMF. I ended up adding a few functions to the library to make things easier.

I also added a DTMF example that shows TX and RX. 

We'll be releasing a new version of the library to Arduino after we make some tweaks to other functionality.
