### ISSUE TITLE
DTMF sketch, codes transmitted seperately, sounds jumbled.

### ISSUE THREAD

**Issue by cjlawson02** [EnhancedRadioDevices/HamShield#41]
I've been trying to make it detect multiple codes in a single serial command and transmit them in one go, but I've been struggling. If I figure it out, I'll PR.

**Comment by mogar** [comment]
I adapted the DTMF example to send all DTMF tones in the buffer before turning off TX. Take a look and let me know if it works for you.

**Comment by cjlawson02** [comment]
Can you add 20ms before the cutoff? last number gets partially cut off. Other than that, works great!

**Comment by cjlawson02** [comment]
also invalid codes break the transmission and don't error in serial

**Comment by mogar** [comment]
Ok, I've updated for both of those issues. LMK what you think.

**Comment by cjlawson02** [comment]
Great. Sorry to be so picky, but 20ms at the beginning would be good too. You have to time it in the loop so that the first one doesn't get cut off. Also, there's a weird noise at the end of each code. Sound file attached; slightly hard to hear but its apparent on the radio. I'll try inspecting with it to see if it affects HT decoding.

**Comment by cjlawson02** [comment]
HT won't decode because the codes aren't sent fast enough 😞

**Comment by mogar** [comment]
What timing does your device need?

Timing on the hamshield is configurable. I'll work on an example of that.

**Comment by mogar** [comment]
I've updated the library with some functions that support manual timing for DTMF. Please take a look at the DTMF example in master and let me know how it works for you.
