### ISSUE TITLE
DTMF sketch, doesn't detect codes

### ISSUE THREAD

**Issue by cjlawson02** [EnhancedRadioDevices/HamShield#42]
Transmitted 25W, headphone jack sounded loud and clear, but monitor didn't show right codes.

**Comment by marcushammar** [comment]
I have also been having issues to decode DTMF. Tried the new code last weekend and it was not working for me properly. Sending DTMF was working with the new code thou.

**Comment by mogar** [comment]
Hmm. What are you using for your transmitter?

You may want to try turning up Volume1 and seeing if that helps.

**Comment by cjlawson02** [comment]
Raising volume 1 creates lots of false positives and no correct reads

**Comment by mogar** [comment]
Is your SQ set correctly?

What are you using for your transmitter? Can it accurately receive DTMF codes from the HamShield?

**Comment by cjlawson02** [comment]
Using SQ in the sketch. 25W is a old kenwood mobile. HT is 5W and Baofeng UV-5X3. Trying receiving/decoding with the HT now.

**Comment by mogar** [comment]
Did you end up getting this working? We've pushed some updates to the DTMF code, but if it's still not working for you I can try to dive a bit deeper on the issue.

**Comment by cjlawson02** [comment]
I haven't tested it yet. I should be able to soon

**Comment by mogar** [comment]
Recent updates seem to be working. Closing this for now. Please re-open if it's still not working for you.

**Comment by AllDigital33** [comment]
Mogar, I've got the same issue with two separate HamShields. I bought the HamShield Mini last Summer connected to an Arduino Due and I had a lot of issues with it receiving and recognizing DTMF tones. It would recognize 1 and 3 and sometimes 6 or 7, but not reliably. It would send DTMF just fine. I then ordered the regular HamShield and paired it with a new Arduino Uno. Using the same example code I get the exact same behavior. I am trying it with a Baofeng UV-5R5 and with a Yaesu VX-8. Both handhelds send great DTMF, sound clean, and trigger local repeaters, so I don't think it is the radios. The issues sound very similar to the issues above. I have tried increasing the volume1, adjusting the squelch, DTMF detect times, etc. but nothing seems to work. I've also swapped out a few different antennas. Please advise.
