### ISSUE TITLE
Issue where RSSI indicator always reads -15

### ISSUE THREAD

**Issue by nigelvh** [EnhancedRadioDevices/HamShield#8]
The RSSI value always is read at -15. Need to determine why and make it return proper values.

**Comment by slepp** [comment]
This was cleared up in the au_updates branch, looks pretty reasonable now.

**Comment by oh7nfc** [comment]
Hi, 

I just got my two HS09 kits today. Interesting piece of work. Both are transmitting when running FMBeacon but the RSSI value is all the time -137 even I transmit with my walkie talkie on the same frequency (433.600 MHz). BTW, where I can get the Auctus 1846S Programming Guide?

73 de Veijo OH3NFC
